spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.120:3306/hzfq_admin_springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
